"""
Change Detection Module for Metric Generator
Implements dual-input detection logic for split YAMLs and validation files
"""

import hashlib
import sys
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Optional

import yaml

# Add parent directory to path for log_usage import
sys.path.append(str(Path(__file__).parent.parent))


class ChangeType(Enum):
    SPLIT_YAML_ONLY = "split_yaml_only"
    VALIDATION_ONLY = "validation_only"
    BOTH_CHANGED = "both_changed"
    NO_CHANGES = "no_changes"


@dataclass
class FileChange:
    filepath: Path
    change_type: str  # "new", "modified", "deleted"
    old_hash: Optional[str] = None
    new_hash: Optional[str] = None


@dataclass
class ChangeDetectionResult:
    change_type: ChangeType
    split_yaml_changes: list[FileChange]
    validation_file_changes: list[FileChange]
    requires_generation: bool


class ChangeDetector:
    """Detects changes in split YAML files and validation files"""

    def __init__(self, root_dir: Path):
        self.root_dir = Path(root_dir)
        self.split_yaml_dir = (
            self.root_dir / "src" / "rocprof_compute_soc" / "analysis_configs"
        )
        self.validation_dir = (
            self.root_dir / "utils" / "metric_generator" / "validation"
        )
        self.hash_file = (
            self.root_dir / "utils" / "metric_generator" / "change_detection_hash.yaml"
        )

        # Known architectures and panels
        self.architectures = [
            "gfx908",
            "gfx90a",
            "gfx940",
            "gfx941",
            "gfx942",
            "gfx950",
        ]
        self.panels = {
            0: "top_stats",
            100: "system_info",
            200: "system_speed_of_light",
            300: "memory_chart",
            400: "roofline",
            500: "command_processor_cpc_cpf",
            600: "workgroup_manager_spi",
            700: "wavefront",
            1000: "compute_units_instruction_mix",
            1100: "compute_units_compute_pipeline",
            1200: "local_data_share_lds",
            1300: "instruction_cache",
            1400: "scalar_l1_data_cache",
            1500: "address_processing_unit_and_data_return_path_ta_td",
            1600: "vector_l1_data_cache",
            1700: "l2_cache",
            1800: "l2_cache_per_channel",
            2100: "pc_sampling",
        }

    def calculate_file_hash(self, filepath: Path) -> str:
        """Calculate SHA256 hash of file content"""
        if not filepath.exists():
            return ""
        return hashlib.sha256(filepath.read_bytes()).hexdigest()

    def load_known_hashes(self) -> dict[str, str]:
        """Load previously recorded file hashes"""
        if not self.hash_file.exists():
            return {}

        try:
            with open(self.hash_file) as f:
                return yaml.safe_load(f) or {}
        except Exception as e:
            print(f"Error loading hash file: {e}")
            return {}

    def save_current_hashes(self, current_hashes: dict[str, str]) -> None:
        """Save current file hashes"""
        try:
            self.hash_file.parent.mkdir(parents=True, exist_ok=True)
            with open(self.hash_file, "w") as f:
                f.write("# AUTOGENERATED FILE. Generated by change detection.\n")
                yaml.dump(current_hashes, f, sort_keys=False)
            print(f"Saved hashes to {self.hash_file}")
        except Exception as e:
            print(f"Failed to save hash file: {e}")

    def scan_split_yaml_files(self) -> dict[str, str]:
        """Scan all split YAML files and return their hashes"""
        current_hashes = {}

        for arch in self.architectures:
            arch_dir = self.split_yaml_dir / arch
            if not arch_dir.exists():
                continue

            for yaml_file in arch_dir.glob("*.yaml"):
                relative_path = yaml_file.relative_to(self.root_dir)
                current_hashes[str(relative_path)] = self.calculate_file_hash(yaml_file)

        return current_hashes

    def scan_validation_files(self) -> dict[str, str]:
        """Scan validation files and return their hashes"""
        if not self.validation_dir.exists():
            return {}

        current_hashes = {}
        validation_files = [
            "metric_templates.yaml",
            "arch_specs.yaml",
            "panel_definitions.yaml",
            "metric_descriptions.yaml",
        ]

        for filename in validation_files:
            filepath = self.validation_dir / filename
            if filepath.exists():
                relative_path = filepath.relative_to(self.root_dir)
                current_hashes[str(relative_path)] = self.calculate_file_hash(filepath)

        return current_hashes

    def detect_file_changes(
        self, current_hashes: dict[str, str], known_hashes: dict[str, str]
    ) -> list[FileChange]:
        """Compare current and known hashes to detect changes"""
        changes = []

        # Check for new and modified files
        for filepath, current_hash in current_hashes.items():
            if filepath not in known_hashes:
                changes.append(
                    FileChange(
                        filepath=Path(filepath),
                        change_type="new",
                        new_hash=current_hash,
                    )
                )
            elif known_hashes[filepath] != current_hash:
                changes.append(
                    FileChange(
                        filepath=Path(filepath),
                        change_type="modified",
                        old_hash=known_hashes[filepath],
                        new_hash=current_hash,
                    )
                )

        # Check for deleted files
        for filepath, old_hash in known_hashes.items():
            if filepath not in current_hashes:
                changes.append(
                    FileChange(
                        filepath=Path(filepath),
                        change_type="deleted",
                        old_hash=old_hash,
                    )
                )

        return changes

    def categorize_changes(
        self, all_changes: list[FileChange]
    ) -> tuple[list[FileChange], list[FileChange]]:
        """Separate changes into split YAML and validation file changes"""
        split_yaml_changes = []
        validation_changes = []

        for change in all_changes:
            if str(change.filepath).startswith(
                "src/rocprof_compute_soc/analysis_configs"
            ):
                split_yaml_changes.append(change)
            elif str(change.filepath).startswith("utils/metric_generator/validation"):
                validation_changes.append(change)

        return split_yaml_changes, validation_changes

    def detect_changes(self) -> ChangeDetectionResult:
        """Main detection logic implementing the dual-input approach"""
        print("Starting change detection...")

        # Load known hashes
        known_hashes = self.load_known_hashes()

        # Scan current files
        split_yaml_hashes = self.scan_split_yaml_files()
        validation_hashes = self.scan_validation_files()
        current_hashes = {**split_yaml_hashes, **validation_hashes}

        # Detect all changes
        all_changes = self.detect_file_changes(current_hashes, known_hashes)

        if not all_changes:
            print("No changes detected")
            return ChangeDetectionResult(
                change_type=ChangeType.NO_CHANGES,
                split_yaml_changes=[],
                validation_file_changes=[],
                requires_generation=False,
            )

        # Categorize changes
        split_changes, validation_changes = self.categorize_changes(all_changes)

        # Determine change type based on our logic
        has_split_changes = len(split_changes) > 0
        has_validation_changes = len(validation_changes) > 0

        if has_split_changes and has_validation_changes:
            change_type = ChangeType.BOTH_CHANGED
        elif has_split_changes:
            change_type = ChangeType.SPLIT_YAML_ONLY
        elif has_validation_changes:
            change_type = ChangeType.VALIDATION_ONLY
        else:
            change_type = ChangeType.NO_CHANGES

        # Log detected changes
        for change in all_changes:
            print(f"Detected {change.change_type}: {change.filepath}")

        # Save current hashes for next run
        self.save_current_hashes(current_hashes)

        return ChangeDetectionResult(
            change_type=change_type,
            split_yaml_changes=split_changes,
            validation_file_changes=validation_changes,
            requires_generation=True,
        )

    def discover_new_architectures(self) -> set[str]:
        """Discover any new architecture directories"""
        if not self.split_yaml_dir.exists():
            return set()

        existing_archs = set()
        for arch_dir in self.split_yaml_dir.iterdir():
            if arch_dir.is_dir() and arch_dir.name.startswith("gfx"):
                existing_archs.add(arch_dir.name)

        known_archs = set(self.architectures)
        new_archs = existing_archs - known_archs

        if new_archs:
            print(f"Discovered new architectures: {', '.join(new_archs)}")

        return new_archs
