"""
Validation File Generator
Generates the split validation files from extracted components
"""

import sys
from pathlib import Path
from typing import Any

import yaml

# Add parent directory to path for log_usage import
sys.path.append(str(Path(__file__).parent.parent))

# Import our component types
from component_extractor import ArchitectureSpec, MetricDefinition, PanelDefinition


class ValidationFileGenerator:
    """Generates split validation files from extracted components"""

    def __init__(self, root_dir: Path):
        self.root_dir = Path(root_dir)
        self.validation_dir = (
            self.root_dir / "utils" / "metric_generator" / "validation"
        )
        self.autogen_header = (
            "# AUTOGENERATED FILE. Only edit for testing purposes, not for development.\n"
            "# Generated from split YAML files by component extraction.\n"
            "# Generated by ValidationFileGenerator\n"
        )

    def generate_metric_templates_yaml(
        self, metric_definitions: dict[str, MetricDefinition]
    ) -> None:
        """Generate metric_templates.yaml"""
        print("Generating metric_templates.yaml...")

        data = {"metrics": {}}

        for metric_name, metric_def in metric_definitions.items():
            template = {
                "formula": metric_def.formula,
                "unit": metric_def.unit,
                "supported_archs": sorted(list(metric_def.supported_archs)),
            }

            if metric_def.peak:
                template["peak"] = metric_def.peak

            if metric_def.arch_overrides:
                template["arch_overrides"] = metric_def.arch_overrides

            data["metrics"][metric_name] = template

        self._write_yaml_file("metric_templates.yaml", data)
        print(f"Generated metric templates for {len(metric_definitions)} metrics")

    def generate_arch_specs_yaml(self, arch_specs: dict[str, ArchitectureSpec]) -> None:
        """Generate arch_specs.yaml"""
        print("Generating arch_specs.yaml...")

        data = {"architectures": {}}

        for arch_name, arch_spec in arch_specs.items():
            spec = {
                "parameters": arch_spec.parameters,
                "supported_metrics": sorted(list(arch_spec.supported_metrics)),
            }

            if arch_spec.metric_overrides:
                spec["metric_overrides"] = arch_spec.metric_overrides

            data["architectures"][arch_name] = spec

        self._write_yaml_file("arch_specs.yaml", data)
        print(f"Generated architecture specs for {len(arch_specs)} architectures")

    def generate_panel_definitions_yaml(
        self, panel_definitions: dict[str, PanelDefinition]
    ) -> None:
        """Generate panel_definitions.yaml"""
        print("Generating panel_definitions.yaml...")

        data = {"panels": []}

        # Sort panels by ID for consistent output
        sorted_panels = sorted(panel_definitions.items(), key=lambda x: int(x[0]))

        for panel_id, panel_def in sorted_panels:
            panel_data = {
                "id": panel_def.id,
                "title": panel_def.title,
                "data_sources": [],
            }

            # Process data sources to remove architecture-specific data
            for data_source in panel_def.data_sources:
                if "metric_table" in data_source:
                    # Simplify metric table to just reference metric names
                    simplified_source = {
                        "type": "metric_table",
                        "id": data_source["metric_table"].get("id"),
                        "title": data_source["metric_table"].get("title"),
                        "header": data_source["metric_table"].get("header", {}),
                        "metrics": sorted(list(panel_def.metrics_used)),
                    }
                    panel_data["data_sources"].append(simplified_source)
                else:
                    # Keep raw CSV tables as-is (they don't have architecture variations)
                    panel_data["data_sources"].append(data_source)

            data["panels"].append(panel_data)

        self._write_yaml_file("panel_definitions.yaml", data)
        print(f"Generated panel definitions for {len(panel_definitions)} panels")

    def generate_metric_descriptions_yaml(
        self, metric_descriptions: dict[str, dict[str, str]]
    ) -> None:
        """Generate metric_descriptions.yaml"""
        print("Generating metric_descriptions.yaml...")

        # Sort descriptions alphabetically for consistency
        sorted_descriptions = dict(sorted(metric_descriptions.items()))

        self._write_yaml_file("metric_descriptions.yaml", sorted_descriptions)
        print(f"Generated descriptions for {len(metric_descriptions)} metrics")

    def _write_yaml_file(self, filename: str, data: Any) -> None:
        """Write data to YAML file with proper formatting"""
        filepath = self.validation_dir / filename

        try:
            # Ensure directory exists
            filepath.parent.mkdir(parents=True, exist_ok=True)

            with open(filepath, "w") as f:
                # Write header
                f.write(self.autogen_header)

                # Write YAML data
                yaml.dump(
                    data,
                    f,
                    sort_keys=False,
                    default_flow_style=False,
                    allow_unicode=True,
                    width=120,
                )

            print(f"Written {filepath}")

        except Exception as e:
            print(f"Failed to write {filepath}: {e}")
            raise

    def generate_all_validation_files(
        self,
        metric_definitions: dict[str, MetricDefinition],
        arch_specs: dict[str, ArchitectureSpec],
        panel_definitions: dict[str, PanelDefinition],
        metric_descriptions: dict[str, dict[str, str]],
    ) -> None:
        """Generate all validation files"""
        print("=== Generating Validation Files ===")

        try:
            self.generate_metric_templates_yaml(metric_definitions)
            self.generate_arch_specs_yaml(arch_specs)
            self.generate_panel_definitions_yaml(panel_definitions)
            self.generate_metric_descriptions_yaml(metric_descriptions)

            print(f"All validation files generated in {self.validation_dir}")

        except Exception as e:
            print(f"Failed to generate validation files: {e}")
            raise


class UnifiedConfigGenerator:
    """Generates unified_config.yaml from validation files for validation purposes"""

    def __init__(self, root_dir: Path):
        self.root_dir = Path(root_dir)
        self.validation_dir = (
            self.root_dir / "utils" / "metric_generator" / "validation"
        )
        self.utils_dir = self.root_dir / "utils"
        self.autogen_header = (
            "# AUTOGENERATED FILE. Only edit for testing purposes, not for development.\n"
            "# Generated from validation files for validation purposes only.\n"
            "# Generated by UnifiedConfigGenerator\n"
            "# NOTE: Please run the generator after making changes to split YAML files\n"
        )

    def load_validation_files(self) -> dict[str, Any]:
        """Load all validation files"""
        validation_files = [
            "metric_templates.yaml",
            "arch_specs.yaml",
            "panel_definitions.yaml",
            "metric_descriptions.yaml",
        ]

        data = {}
        for filename in validation_files:
            filepath = self.validation_dir / filename
            if filepath.exists():
                try:
                    with open(filepath) as f:
                        data[filename.replace(".yaml", "")] = yaml.safe_load(f)
                except Exception as e:
                    print(f"Failed to load {filepath}: {e}")
                    data[filename.replace(".yaml", "")] = {}
            else:
                print(f"Validation file not found: {filepath}")
                data[filename.replace(".yaml", "")] = {}

        return data

    def generate_unified_config(self) -> None:
        """Generate unified_config.yaml from validation files"""
        print("Generating unified_config.yaml from validation files...")

        try:
            validation_data = self.load_validation_files()

            # Build unified config structure
            unified_config = {"panels": []}

            # Get data from validation files
            metric_templates = validation_data.get("metric_templates", {}).get(
                "metrics", {}
            )
            arch_specs = validation_data.get("arch_specs", {}).get("architectures", {})
            panel_definitions = validation_data.get("panel_definitions", {}).get(
                "panels", []
            )
            metric_descriptions = validation_data.get("metric_descriptions", {})

            # Process each panel
            for panel_def in panel_definitions:
                panel = {
                    "id": panel_def.get("id"),
                    "title": panel_def.get("title"),
                    "data source": [],
                    "metrics_description": {},
                }

                # Process data sources
                for data_source_def in panel_def.get("data_sources", []):
                    if data_source_def.get("type") == "metric_table":
                        # Build metric table with architecture-specific data
                        metric_table = {
                            "metric_table": {
                                "id": data_source_def.get("id"),
                                "title": data_source_def.get("title"),
                                "header": data_source_def.get("header", {}),
                                "metric": {},
                            }
                        }

                        # Add metrics for each architecture
                        for arch_name, arch_config in arch_specs.items():
                            metric_table["metric_table"]["metric"][arch_name] = {}

                            for metric_name in data_source_def.get("metrics", []):
                                if metric_name in arch_config.get(
                                    "supported_metrics", []
                                ):
                                    metric_template = metric_templates.get(
                                        metric_name, {}
                                    )

                                    # Start with template data
                                    metric_data = {
                                        "value": metric_template.get("formula", ""),
                                        "unit": metric_template.get("unit", ""),
                                    }

                                    if "peak" in metric_template:
                                        metric_data["peak"] = metric_template["peak"]
                                        metric_data["pop"] = (
                                            f"((100 * {metric_data['value']}) / {metric_data['peak']})"
                                        )

                                    # Apply architecture-specific overrides
                                    if metric_name in arch_config.get(
                                        "metric_overrides", {}
                                    ):
                                        overrides = arch_config["metric_overrides"][
                                            metric_name
                                        ]
                                        metric_data.update(overrides)

                                    metric_table["metric_table"]["metric"][arch_name][
                                        metric_name
                                    ] = metric_data

                                    # Add description to panel
                                    if metric_name in metric_descriptions:
                                        panel["metrics_description"][metric_name] = (
                                            metric_descriptions[metric_name]
                                        )

                        panel["data source"].append(metric_table)
                    else:
                        # Raw CSV table - add as-is
                        panel["data source"].append(data_source_def)

                unified_config["panels"].append(panel)

            # Write unified config
            filepath = self.utils_dir / "unified_config.yaml"
            with open(filepath, "w") as f:
                f.write(self.autogen_header)
                yaml.dump(
                    unified_config,
                    f,
                    sort_keys=False,
                    default_flow_style=False,
                    allow_unicode=True,
                    width=120,
                )

            print(f"Generated unified_config.yaml at {filepath}")

        except Exception as e:
            print(f"Failed to generate unified config: {e}")
            raise
